//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabryka2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maszyny()
        {
            this.Operatorzy = new HashSet<Operatorzy>();
        }
    
        public int Id { get; set; }
        public string Maszyna_Nazwa { get; set; }
        public Nullable<decimal> Numer_ewidencji { get; set; }
        public Nullable<System.DateTime> Data_uruchomienia { get; set; }
        public int HalaId { get; set; }
        public int HaleId { get; set; }
    
        public virtual Hale Hale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operatorzy> Operatorzy { get; set; }
    }
}
